# Sadece Redis
# docker compose -f docker-compose.redis.yml up -d

services:
  redis:
    image: redis:7-alpine
    container_name: redis
    restart: unless-stopped
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 20
    networks:
      - agesa_net

volumes:
  redis_data:

networks:
  agesa_net:
    external: true
