# Redis
# docker compose -f docker-compose.redis.yml up -d

services:
  redis:
    image: redis:7-alpine
    container_name: redis
    restart: always
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data
    networks:
      - n8n_network

volumes:
  redis_data:

networks:
  n8n_network:
    external: true
